version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'cron'
      cronjob: '0 10 1,15 * *'
      timezone: 'America/New_York'
    open-pull-requests-limit: 5
    cooldown:
      default-days: 4
    groups:
      npm-patch-updates:
        update-types: ['patch']
      npm-minor-updates:
        update-types: ['minor']
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
