name: Pull Request Checker

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{github.repository_id}}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0

      - name: Install npm dependencies
        run: npm ci

        # Run linting
      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test
