name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically marked as stale due to inactivity. Please comment if you want to keep it open.'
          stale-pr-message: 'This pull request has been automatically marked as stale due to inactivity.'
          close-issue-message: 'Closing this issue due to prolonged inactivity.'
          close-pr-message: 'Closing this pull request due to inactivity.'
          days-before-stale: 30
          days-before-close: 7
          exempt-issue-labels: 'inspecting'
          
